[global]
# Where to save temporary files produces between Python file runs
working_dir = "/mnt/d/working/"
# The file name prefix for those temporary files
meta_save_prefix = "abo-listings-"
# Where the ABO dataset is located. See documentation for details.
abo_dataset_dir = "/mnt/d/abo-dataset/"

[english_check]
# Whether to run Google Cloud language detection. See documentation for requirements.
cloud_language_detection = true

[product_type_verification]
# The name to save the checkpoint file as in working_dir
checkpoint_name = "abo-category-check.pkl"

[embed_to_chroma]
# Directory where the BLIP-2 models are located
models_dir = "/mnt/d/models/"
# BLIP-2 model to use for multimodal embeddings. Provided options are'gs', 'abo', 'pretrain', or 'coco'.
model_selection = "gs"
# Device to run BLIP-2 on. Options are usually "cuda" or "cpu."
model_device = "cuda"
# Where to save the temporary embeddings files
embeddings_dir = "/mnt/d/embeddings/"
# Batch size for processing embeddings through model
batch_size = 64
# Directory where Chroma database is to be stored
chroma_dir = "/mnt/d/chroma/"
