services:
  ui:
    build:
      context: ..
      dockerfile: docker/ui.dockerfile
    ports:
      - ${UI_PORT}:${UI_PORT}
    depends_on:
      agent:
        condition: service_started

  agent:
    env_file: ".env"
    build:
      context: ..
      dockerfile: docker/agent.dockerfile
    volumes:
      - ${HF_LOCAL}:${HF_HOME}
      - ${DB_LOCAL}:${DB_CONTAINER}
      - ${ABO_DIR_LOCAL}:${ABO_DIR_CONTAINER}:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      blip-2:
        condition: service_started
      ollama:
        condition: service_started

  blip-2:
    env_file: ".env"
    build:
      context: ..
      dockerfile: docker/blip-2.dockerfile
    volumes:
      - ${MODELS_DIR_LOCAL}:${MODELS_DIR_CONTAINER}:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama
    volumes:
      - ${OLLAMA_LOCAL}:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]




