services:
  ui:
    build:
      context: ..
      dockerfile: docker/ui.dockerfile
    ports:
      - ${UI_PORT}:${UI_PORT}
    depends_on:
      agent:
        condition: service_started

  agent:
    env_file: ".env"
    build:
      context: ..
      dockerfile: docker/agent.dockerfile
    volumes:
      - ${ABO_DIR_LOCAL}:${ABO_DIR_CONTAINER}:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      blip-2:
        condition: service_started
      ollama:
        condition: service_started
      chroma:
        condition: service_started

  chroma:
    image: chromadb/chroma
    volumes: 
      - ${CHROMA_DIR_LOCAL}:/chroma/chroma

  blip-2:
    env_file: ".env"
    build:
      context: ..
      dockerfile: docker/blip-2.dockerfile
    volumes:
      - ${MODELS_DIR_LOCAL}:${MODELS_DIR_CONTAINER}:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama
    volumes:
      - ${OLLAMA_LOCAL}:/root/.ollama
    command: /bin/ollama pull ${OLLAMA_MODEL} && /bin/ollama serve
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]




